### ISSUE TITLE
Problem with send command from Bungee to client server

### ISSUE THREAD

**Issue by hazae41** [RHazDev/CommandsDispatcher#1]
_From @xCraftRayX on October 17, 2018 22:24_

From bungee to client is not working, but from client to bungee is working.
For latest version of sockets, dispatch and kotlin
Logs from bungee: https://pastebin.com/wBier8an
And on the lobby:  `[Sockets4MC] §aThe connection Lobby<->Bungee is available`

And on the lobby like a player when I used: /bdispatch lobby "say test" it is working, but when I used /dispatch lobby "say test" is not working.

_Copied from original issue: RHazDev/Sockets4MC#2_

**Comment by hazae41** [comment]
Thanks for your report

**Comment by hazae41** [comment]
_From @xCraftRayX on October 22, 2018 18:26_

When will be update which fixed this problem?

**Comment by hazae41** [comment]
@xCraftRayX 
Please try using BungeeCord as the client and Spigot as the server

**Comment by TheFonsi** [comment]
Okay, tomorrow I will be can send result.

**Comment by TheFonsi** [comment]
It's work but only for Bungee like Clieant and my Lobby server like Server in config.
I use command from lobby: /dispatch Bungee glist and next /bdispatch Bungee glist

`02:01:11 [INFO] xCraftRayX executed command: /dispatch Bungee glist
02:01:11 [INFO] [Sockets4MC] Bungee ---> {"password":"xksdvc0w3d93vjc39123","sender":"Bungee","channel":"CDispatch","fake":"null","command":"glist","player":"xCraftRayX","target":"Bungee"}
02:01:13 [INFO] [Sockets4MC] Bungee <--- 698#{"channel":"CMessage","message":"Cannot find target: Bungee","sender":"Bungee","target":"Lobby","p
02:01:14 [INFO] [Sockets4MC] Bungee <--- 698#layer":"xCraftRayX"}
02:01:15 [INFO] [Sockets4MC] Bungee <--- 698#--end--
02:01:26 [INFO] [Sockets4MC] Bungee <--- 389#{"channel":"CDispatch"}
02:01:27 [INFO] [Sockets4MC] Bungee <--- 389#--end--
`
But in bungee console I entered: /dispatch Lobby "say Hello" and  was working ;)

**Comment by hazae41** [comment]
Please try with this build
https://github.com/RHazDev/CommandsDispatcher/raw/master/jar/cmdispatcher-3.0.3.jar
It should send you some debug messages and fix the "cannot find target"

**Comment by TheFonsi** [comment]
Only work if Bungee is client and Spigot is server using /dispatch TARGET COMMAND
And bdispatch with that conf. haven't sense :P

But if I use Bungee like Server and Spigot like Client and If I sent:
`/dispatch Lobby "say test"
23:25:41 [INFO] [Sockets4MC] Bungee ---> {"channel":"CDispatch"}
23:25:41 [INFO] Dispatching to [Lobby]...
`
Plugin do nothink.
If I sent from Spigot: /bdispatch TARGET COMMAND - it's work for Bungee and Lobby target.
But if I sent from Spigot: /dispatch TARGET COMMAND -  For target Lobby work, For target Bungee does't work.
And if I sent from Spigot: /bdispatch Bungee COMMAND - it's work

**Comment by hazae41** [comment]
Do you have debugs when you send commands from server to client?

**Comment by hazae41** [comment]
Also, please try with multiple commands on the same line

**Comment by TheFonsi** [comment]
Yes I have ON debug mode on Client and Server.
When I send command from Server to Client on Client console we can see:
[00:35:41 INFO]: [Sockets4MC] Lobby <--- 165#{"channel":"CDispatch"}
[00:35:42 INFO]: [Sockets4MC] Lobby <--- 165#--end--

**Comment by hazae41** [comment]
And what do you see on Server console?

**Comment by TheFonsi** [comment]
`>dispatch Lobby "say hello"
00:56:53 [INFO] CONSOLE executed command: /dispatch Lobby "say hello"
00:56:53 [INFO] [Sockets4MC] Bungee ---> {"channel":"CDispatch"}
00:56:53 [INFO] Dispatching to [Lobby]...
`

**Comment by hazae41** [comment]
Try with this build please
https://github.com/RHazDev/CommandsDispatcher/raw/master/jar/cmdispatcher-3.0.3.jar

**Comment by TheFonsi** [comment]
`04:23:29 [INFO] CONSOLE executed command: /dispatch Lobby "say hello"
04:23:29 [INFO] [Sockets4MC] Bungee ---> {"channel":"CDispatch"}
04:23:29 [INFO] command: say hello
04:23:29 [INFO] player: CONSOLE
04:23:29 [INFO] sender: Bungee
04:23:29 [INFO] target: Lobby
04:23:29 [INFO] fake: null
04:23:29 [INFO] Dispatching to [Lobby]...
`
And nothing.

And that same situation when I send command like player from Lobby to Lobby.
But player is my nick and sender is Bungee.

**Comment by hazae41** [comment]
Try with:
- "lobby" instead of "Lobby" 
- "--as <your nick>" before all args

**Comment by TheFonsi** [comment]
I canged Lobby from config to lobby and for that command: `/dispatch lobby say --as hello test` I get: https://scr.hu/AO1DlMG

And from Bungee: 20:33:27 [INFO] CONSOLE executed command: /dispatch lobby say --as hello test
20:33:27 [INFO] command: say
20:33:27 [INFO] player: CONSOLE
20:33:27 [INFO] sender: Bungee
20:33:27 [INFO] target: lobby
20:33:27 [INFO] fake: hello
20:33:27 [INFO] [Sockets4MC] Bungee ---> {"channel":"CDispatch"}
20:33:27 [INFO] command: test
20:33:27 [INFO] player: CONSOLE
20:33:27 [INFO] sender: Bungee
20:33:27 [INFO] target: lobby
20:33:27 [INFO] [Sockets4MC] Bungee ---> {"channel":"CDispatch"}
20:33:27 [INFO] fake: hello
20:33:27 [INFO] Dispatching to [lobby]...

**Comment by hazae41** [comment]
### Fixed
CMDispatch https://github.com/RHazDev/CommandsDispatcher/commit/6f82b54276231d37386450c9567fa317db42a059
Sockets4MC https://github.com/RHazDev/Sockets4MC/commit/84226796661b7ec9f77bbdc41029027db46e62e9
Sockets https://github.com/RHazDev/RHazSockets/commit/c36c98fd4420e2a873f43c7bf2b9a1fb6f8fe7dc
